title: "Your Blog Title"
email: "your-email@example.com"
description: "A description of your site"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

sass:
  sass_dir: assets/css
  style: compressed

# Build settings
markdown: kramdown
